# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{assembla}
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ignacy Moryc"]
  s.date = %q{2010-03-15}
  s.default_executable = %q{ass}
  s.description = %q{This gem provides access to assembla tickets. It supports listing, creating and modyfing functionality}
  s.email = %q{imoryc@gmail.com}
  s.executables = ["ass"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "README.textile",
     "Rakefile",
     "VERSION",
     "a2smbla-0.3.0.gem",
     "assembla.gemspec",
     "bin/ass",
     "config_default.yml",
     "lib/assembla.rb",
     "lib/extensions.rb",
     "lib/interpreter.rb",
     "lib/ticket.rb",
     "rdoc/classes/AssEmBlr.html",
     "rdoc/created.rid",
     "rdoc/files/README_textile.html",
     "rdoc/files/lib/assembla_rb.html",
     "rdoc/fr_class_index.html",
     "rdoc/fr_file_index.html",
     "rdoc/fr_method_index.html",
     "rdoc/index.html",
     "rdoc/rdoc-style.css",
     "spec/assembla_spec.rb",
     "spec/mock.html",
     "spec/test_config.yml"
  ]
  s.homepage = %q{http://github.com/ignacy/assembla}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Command line access to assembla}
  s.test_files = [
    "spec/assembla_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8.1"])
    else
      s.add_dependency(%q<hpricot>, [">= 0.8.1"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0.8.1"])
  end
end

